### ISSUE TITLE
'numpy/arrayobject.h' file not found

### ISSUE THREAD

**Issue by yosefrajwulf** [nathanshammah/piqs#59]
I have installed both piqs and qutip via source compilation in MacOS 10.13.6. I am using Qutip 4.3.1 and piqs 1.2. If I run the following
` from qutip import *`
` from qutip.piqs import *`
I get an error message:

> fatal error: 'numpy/arrayobject.h' file not found
> #include "numpy/arrayobject.h"

Could someone please help me fix this?

**Comment by sahmed95** [comment]
Hi, this seems to be mostly related to incorrect numpy installation or a
mismatch. Could you remove qutip, update your numpy and try again?

Alternatively, the best way to manage packages would be using anaconda. You
could install Miniconda and reinstall qutip with `conda install -c
conda-forge qutip`. This way all your packages will be kept updated and in
sync. Since numpy as well as qutip rely on some C/C++ bindings, sometimes
installing the incorrect binaries can lead to this type of errors.

**Comment by yosefrajwulf** [comment]
Reinstalling did not work for me. However,  a workaround that did work (a vile hack one might say) is the following:
1) cd /usr/local/include
2) ln -s /usr/local/lib/python2.7/site-packages/numpy/core/include/numpy numpy

**Comment by yosefrajwulf** [comment]
Thanks for the help @sahmed95 ! I will close the issue now.

**Comment by sahmed95** [comment]
Great. In future, conda might be helpful. Let us know if you face any more
issues.

**Comment by nathanshammah** [comment]
Thank you @sahmed95 and thanks for getting in touch here @yosefrajwulf.
